// Generated by CoffeeScript 1.11.1
(function() {
  var assert, should, user;

  assert = require('assert');

  should = require('should');

  user = require('../lib/user');

  describe('Array', function() {
    describe('#get()', function() {
      it('should call the callback function', function() {
        var myfunc;
        myfunc = user.get('willson', function(user) {
          return user;
        });
        should.equal(myfunc, 'willson');
      });
    });
  });

}).call(this);
